import { Crimson_Text } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const crimsonText = Crimson_Text({
  variable: "--font-crimson-text",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Design Team Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${crimsonText.variable} antialiased`}>
        <div style={{
          position: "fixed",
          top: 0,
          left: 0,
          width: "100%",
          zIndex: 50,
          background: "#e4dfda"
        }}>
          <Nav />
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
